# nixpacks.toml configuration for MERN backend only

[phases.setup]
nixPkgs = ["nodejs_20", "nodejs.npm"]

[phases.install]
cmds = [
  "cd server && npm ci"
]

[phases.build]
cmds = [
  "cd server && npm prune --production"
]

[start]
cmd = "cd server && node index.js"

[variables]
NODE_ENV = "production"